---
# This descriptor is used in local mode to describe how shape of configuration of the policy needs to be.
apiVersion: gateway.mulesoft.com/v1alpha1
kind: Extension
metadata:
  name: simplest-header-injection
spec:
  extends:
    - name: extension-definition
    - name: envoy-filter
    - name: proxy-wasm-filter
  properties:
    {% if useconfig -%}
    header_name:
      type: string
    {% endif -%}
   #Required fields for wasm based policies
    rootId:
      type: string
      default: main
    implementation:
      type: string
      default: base64://<ENCODED>
  required:
    - header_name

